{
 "title": "Main profiling dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "process_name",
    "label": "Process name",
    "query": "select distinct process_name from profiling.processes order by process_name;"
   },
   {
    "name": "start_time",
    "label": "Start time",
    "query": "SELECT 'value: ' || start_time || ', text: ' || TO_TIMESTAMP(start_time / 1000000000) FROM profiling.processes WHERE process_name = '$process_name' order by start_time desc;"
   },
   {
    "name": "process_id",
    "label": "[Debug] process_id",
    "query": "SELECT process_id from profiling.processes where process_name = '$process_name' and start_time = '$start_time'"
   },
   {
    "name": "max_rss_ts",
    "label": "Max RSS timestamp",
    "query": "SELECT toString(argMaxMerge(peak_ts)) AS peak_ts\nFROM profiling.memory_peaks\nWHERE \nvalue_type = 'active_size' and process_id = ${process_id}\n"
   },
   {
    "name": "first_point_in_range",
    "query": "SELECT\n    min(timestamp) || '' as point\nFROM\n    profiling.timeseries\nWHERE\n    process_id == ${process_id}\n    AND value_type == 'active_size'\n    AND label_id == 0\n    AND timestamp >= $__fromTime_ms"
   },
   {
    "name": "possible_functions",
    "query": "SELECT\n    'value:' || label_id || '###text:' || label || ':' || library || ':' || location\nFROM\n    profiling.localized_name\nWHERE\n    process_id == ${process_id}\nORDER BY label_id ASC"
   },
   {
    "name": "process_pid",
    "query": "select process_pid from profiling.processes where process_id = '$process_id';"
   }
  ]
 },
 "panels": [
  { "title": "Set actual time for process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Set actual process time",
   "type": "williamvenner-timepickerbuttons-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  subtractSeconds(min(timestamp), 5) as time_from,\n  addSeconds(max(timestamp), 5) as time_to\nFROM\n  profiling.timeseries\nWHERE\n  process_id == ${process_id}\n  AND value_type == 'active_size'\n  AND label_id == 0\n;"
    }
   ]
  },
  {
   "title": "Memory peak",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peak rss flamegraph (all time)",
     "type": "flamegraph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "WITH (\n    SELECT\n        argMaxMerge(peak_ts) as peak_ts\n    FROM\n        profiling.memory_peaks\n    WHERE\n        process_id == ${process_id}\n        AND value_type == 'active_size'\n) as max_rss\nSELECT\n    *\nFROM\n    flamegraph_view(\n        process_id = ${process_id},\n        value_type = 'active_size',\n        diff_sign = 1,\n        pass_all = True, \n        from_time = '1970-01-01',\n        to_time = '${max_rss_ts}'\n    );"
      }
     ]
    },
    {
     "title": "Total memory consumption",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "WITH (\n    SELECT\n        argMaxMerge(peak_ts) as peak_ts\n    FROM\n        profiling.memory_peaks\n    WHERE\n        process_id == ${process_id}\n        AND value_type == 'active_size'\n) as max_rss\nSELECT\n    total_value,\n    self_value,\n    label,\n    library,\n    location\nFROM (\n    SELECT\n        label_id,\n        argMax(self_value, timestamp) as self_value,\n        argMax(total_value, timestamp) as total_value\n    FROM\n        \"profiling\".\"timeseries\"\n    WHERE \n        ( timestamp <= max_rss )\n        AND ( process_id = $process_id )\n        AND value_type = 'active_size'\n    GROUP BY (label_id)\n) as diffs\nINNER JOIN (\n    SELECT\n        label_id,\n        label,\n        location,\n        library\n    FROM\n        localized_name\n    WHERE\n        process_id = $process_id\n) as names\nON diffs.label_id == names.label_id\nORDER BY total_value DESC"
      }
     ]
    }
   ]
  },
  { "title": "Total consumption timeseries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeInterval_ms(timestamp) as \"time\",\n    max(total_value) as rss\nFROM\n    \"profiling\".\"timeseries\"\nWHERE \n    $__timeFilter_ms(timestamp)\n    AND ( process_id = $process_id )\n    AND label_id = 0\n    AND value_type = 'active_size'\nGROUP BY (\"time\")\nORDER BY \"time\" ASC\n;"
    }
   ]
  },
  {
   "title": "Active allocations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeInterval_ms(timestamp) as \"time\",\n    max(total_value) as active_allocations\nFROM\n    \"profiling\".\"timeseries\"\nWHERE \n    $__timeFilter_ms(timestamp)\n    AND ( process_id = $process_id )\n    AND label_id = 0\n    AND value_type = 'active_count'\nGROUP BY (\"time\")\nORDER BY \"time\" ASC\n;"
    }
   ]
  },
  {
   "title": "Inspect change in memory consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Addition (in time)",
     "type": "flamegraph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "SELECT\n    *\nFROM\n    flamegraph_view(\n        process_id = ${process_id},\n        value_type = 'active_size',\n        diff_sign = 1,\n        pass_all = False, \n        from_time = '${first_point_in_range}',\n        to_time = $__toTime_ms\n    );"
      }
     ]
    },
    {
     "title": "Remove (in time)",
     "type": "flamegraph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "SELECT\n    *\nFROM\n    flamegraph_view(\n        process_id = ${process_id},\n        value_type = 'active_size',\n        diff_sign = -1,\n        pass_all = False, \n        from_time = '${first_point_in_range}',\n        to_time = $__toTime_ms\n    );"
      }
     ]
    },
    {
     "title": "Memory consumption change",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "\nSELECT\n    total_value_diff,\n    self_value_diff,\n    label,\n    library,\n    location\nFROM (\n    SELECT\n        label_id,\n        to.total_value - from.total_value as total_value_diff,\n        to.self_value - from.self_value as self_value_diff\n    FROM (\n        SELECT\n            label_id,\n            argMax(self_value, timestamp) as self_value,\n            argMax(total_value, timestamp) as total_value\n        FROM\n            \"profiling\".\"timeseries\"\n        WHERE \n            ( timestamp <= $__toTime_ms )\n            AND ( process_id = $process_id )\n            AND value_type = 'active_size'\n        GROUP BY (label_id)\n    ) as to\n    LEFT JOIN (\n        SELECT\n            label_id,\n            argMax(self_value, timestamp) as self_value,\n            argMax(total_value, timestamp) as total_value\n        FROM\n            \"profiling\".\"timeseries\"\n        WHERE \n            ( timestamp <= toDateTime64('${first_point_in_range}',9))\n            AND ( process_id = $process_id )\n            AND value_type = 'active_size'\n        GROUP BY (label_id)\n    ) as from\n    ON to.label_id == from.label_id\n    WHERE total_value_diff != 0\n) as diffs\nINNER JOIN (\n    SELECT\n        label_id,\n        label,\n        location,\n        library\n    FROM\n        localized_name\n    WHERE\n        process_id = $process_id\n) as names\nON diffs.label_id == names.label_id\nORDER BY total_value_diff DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Inspect memory consumption per function",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Selecting",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 911 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Memory consumption (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 911 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "SELECT \n    *\nFROM \n    timeseries_view(\n        process_id = ${process_id},\n        value_type = 'active_size', \n        from_time = $__fromTime_ms,\n        to_time= $__toTime_ms,\n        interval_ms=$__interval_ms,\n        labels = [${possible_functions:raw}]\n    );"
      }
     ]
    }
   ]
  },
  {
   "title": "Inspect change in active allocations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Addition (in time) (count)",
     "type": "flamegraph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 926 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "rawSql": "SELECT\n    *\nFROM\n    flamegraph_view(\n        process_id = ${process_id},\n        value_type = 'active_count',\n        diff_sign = 1,\n        pass_all = False, \n        from_time = '${first_point_in_range}',\n        to_time = $__toTime_ms\n    );"
      }
     ]
    },
    {
     "title": "Remove (in time) (count)",
     "type": "flamegraph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 926 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "rawSql": "SELECT\n    *\nFROM\n    flamegraph_view(\n        process_id = ${process_id},\n        value_type = 'active_count',\n        diff_sign = -1,\n        pass_all = False, \n        from_time = '${first_point_in_range}',\n        to_time = $__toTime_ms\n    );"
      }
     ]
    },
    {
     "title": "Allocations count change",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 942 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "rawSql": "\nSELECT\n    total_value_diff,\n    self_value_diff,\n    label,\n    library,\n    location\nFROM (\n    SELECT\n        label_id,\n        to.total_value - from.total_value as total_value_diff,\n        to.self_value - from.self_value as self_value_diff\n    FROM (\n        SELECT\n            label_id,\n            argMax(self_value, timestamp) as self_value,\n            argMax(total_value, timestamp) as total_value\n        FROM\n            \"profiling\".\"timeseries\"\n        WHERE \n            ( timestamp <= $__toTime_ms )\n            AND ( process_id = $process_id )\n            AND value_type = 'active_count'\n        GROUP BY (label_id)\n    ) as to\n    LEFT JOIN (\n        SELECT\n            label_id,\n            argMax(self_value, timestamp) as self_value,\n            argMax(total_value, timestamp) as total_value\n        FROM\n            \"profiling\".\"timeseries\"\n        WHERE \n            ( timestamp <= toDateTime64('${first_point_in_range}',9))\n            AND ( process_id = $process_id )\n            AND value_type = 'active_count'\n        GROUP BY (label_id)\n    ) as from\n    ON to.label_id == from.label_id\n    WHERE total_value_diff != 0\n) as diffs\nINNER JOIN (\n    SELECT\n        label_id,\n        label,\n        location,\n        library\n    FROM\n        localized_name\n    WHERE\n        process_id = $process_id\n) as names\nON diffs.label_id == names.label_id\nORDER BY total_value_diff DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Inspect active allocations per function",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Selecting",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 214 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Active allocations",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "rawSql": "SELECT \n    *\nFROM \n    timeseries_view(\n        process_id = ${process_id},\n        value_type = 'active_count', \n        from_time = $__fromTime_ms,\n        to_time = $__toTime_ms,\n        interval_ms = $__interval_ms,\n        labels = [${possible_functions:raw}]\n    );"
      }
     ]
    }
   ]
  },
  {
   "title": "Cumulative allocations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cumulative memory allocated",
     "type": "flamegraph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "SELECT\n    *\nFROM\n    flamegraph_view(\n        process_id = ${process_id},\n        value_type = 'total_size',\n        diff_sign = 1,\n        pass_all = True, \n        from_time = '1970-01-01',\n        to_time = '2199-01-01'\n    );"
      }
     ]
    },
    {
     "title": "Cumulative allocations count",
     "type": "flamegraph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "rawSql": "SELECT\n    *\nFROM\n    flamegraph_view(\n        process_id = ${process_id},\n        value_type = 'total_count',\n        diff_sign = 1,\n        pass_all = True, \n        from_time = '1970-01-01',\n        to_time = '2199-01-01'\n    );"
      }
     ]
    }
   ]
  }
 ]
}