services:

  memhawk_postgres:
    image: postgres:18-trixie
    container_name: memhawk_postgres
    restart: unless-stopped
    networks:
      - memhawk_monitoring_net
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - memhawk_postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  memhawk_clickhouse:
    image: clickhouse/clickhouse-server:25.10
    container_name: memhawk_clickhouse
    restart: unless-stopped
    networks:
      - memhawk_monitoring_net
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-admin}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-admin}
    volumes:
      - ./clickhouse/scripts:/docker-entrypoint-initdb.d
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/custom.xml
      - memhawk_clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/udfs:/var/lib/clickhouse/user_scripts
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"
      - "${CLICKHOUSE_NATIVE_PORT:-9000}:9000"

  memhawk_grafana:
    container_name: memhawk_grafana
    restart: unless-stopped
    build:
      context: ./grafana
      dockerfile: Dockerfile
      network: host
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    depends_on:
      - memhawk_clickhouse
    networks:
      - memhawk_monitoring_net
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/profiling.json
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - memhawk_grafana_data:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"

volumes:
  memhawk_clickhouse_data:
  memhawk_postgres_data:
  memhawk_grafana_data:

networks:
  memhawk_monitoring_net:
    driver: bridge
