apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: PDEE91DDB90597936
    jsonData:
      defaultDatabase: profiling
      host: memhawk_clickhouse
      port: 9000
      protocol: native 
      secure: false
      username: admin
    secureJsonData:
      password: admin
    editable: true
  
  - name: Postgres
    type: grafana-postgresql-datasource
    access: proxy
    uid: af8746j674npce
    url: memhawk_postgres:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: ""
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
