name: Build on Commit

on:
  push:
    branches:
      - '**'  # Triggers on every branch
env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            build-essential \
            gcc-9 g++-9 \
            cmake git \
            libtool autoconf unzip wget \
            libboost-container-dev \
            software-properties-common lsb-release

      - name: Update CMake
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
          sudo apt update -y && \
          sudo apt install -y cmake


      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/artifacts

      - name: Build project
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # - name: Run tests
      #   run: |
      #     cd build
      #     ctest --output-on-failure
